SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZZ1_SysLibreExt](
	[CB_File] [varchar](128) NOT NULL,
	[CB_Name] [varchar](128) NOT NULL,
	[CB_Pos] [smallint] NOT NULL,
	[IsMultiline] [bit] NOT NULL,
	[IsReadOnly] [bit] NOT NULL,
 CONSTRAINT [PK_ZZ1_SysLibreExt] PRIMARY KEY CLUSTERED 
(
	[CB_File] ASC,
	[CB_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZZ1_SysLibreExt] ADD  CONSTRAINT [DF_ZZ1_SysLibreExt_IsMultiline]  DEFAULT ((0)) FOR [IsMultiline]
GO

ALTER TABLE [dbo].[ZZ1_SysLibreExt] ADD  CONSTRAINT [DF_ZZ1_SysLibreExt_IsReadOnly]  DEFAULT ((0)) FOR [IsReadOnly]
GO